//use the upper case 
export const ActionTypes =
{
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
SET_PRODUCTS :"SET_PRODUCTS",
SELECTED_PRODUCT : "SELECTED_PRODUCT",
REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
ADDITEM :"ADDITEM",
DELITEM : "DELITEM",
// addCart, delCart
};